# Generated by Django 3.2.25 on 2025-01-11 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foremen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreman',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
