# Generated by Django 3.2.25 on 2025-01-11 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foremen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('lrv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serial_no', models.CharField(blank=True, max_length=50)),
                ('interval', models.IntegerField()),
                ('last_checked', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('history', models.TextField()),
                ('data_sheet', models.FileField(blank=True, null=True, upload_to='data_sheets/')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foremen.foreman')),
            ],
        ),
    ]
